import { FormationCardProps } from "../../stories/Cards/FormationCard/FormationCard";

export const formations: FormationCardProps[] = [
  {
    title: 'Formació 1',
    summary: 'This is a formation card. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat sed voluptates, nobis iure veniam animi magni assumenda eos ipsam quos. Tenetur, error alias?',
    img: 'https://picsum.photos/seed/picsum/200/300',
    modality: 'Presencial',
    lenguage: 'Català',
    price: 'Gratuït',
    duration: '20 hores',
    methodology: 'Casos pràctics',
    organization: 'Organització 1',
    startDate: '01/01/2021',
    endDate: '01/02/2021',
    teachers: ['Teacher 1', 'Teacher 2'],
    level: 'Avançat',
  },
  {
    title: 'Formació 2',
    summary: 'This is a formation card. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat sed voluptates, nobis iure veniam animi magni assumenda eos ipsam quos. Tenetur, error alias?',
    img: 'https://picsum.photos/seed/picsum/200/300',
    modality: 'Online',
    lenguage: 'Català',
    price: '230',
    duration: '20 hores',
    methodology: 'Casos pràctics',
    organization: 'Organització 2',
    startDate: '01/01/2021',
    endDate: '01/02/2021',
    teachers: ['Teacher 1', 'Teacher 2'],
    level: 'Bàsic',
  },
  {
    title: 'Formació 3',
    summary: 'This is a formation card. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat sed voluptates, nobis iure veniam animi magni assumenda eos ipsam quos. Tenetur, error alias?',
    img: 'https://picsum.photos/seed/picsum/200/300',
    modality: 'Presencial',
    lenguage: 'Català',
    price: 'Gratuït',
    duration: '20 hores',
    methodology: 'Casos pràctics',
    organization: 'Organització 3',
    startDate: '01/01/2021',
    endDate: '01/02/2021',
    teachers: ['Teacher 1', 'Teacher 2'],
    level: 'Mitjà',
  },
];