import { FormationCardProps } from "../../stories/Cards/FormationCard/FormationCard";

export const formations: FormationCardProps[] = [
  {
    title: 'Postgrau en Gestió de la Transició Sostenible i l\'Emergència Climàtica',
    summary: 'El impacto sobre el medioambiente puede reducirse. Debemos tomar decisiones con criterios de sostenibilidad porque el futuro de las empresas es verde. Está en tus manos liderar el cambio.',
    img: 'https://picsum.photos/seed/picsum/200/300',
    modality: ['Presencial', 'Online'],
    // address: 'Pg. Pujades, 1 (08003 Barcelona, Espanya)',
    lenguage: ['Castellà', 'Anglès'],
    price: '2.800€',
    duration: '160 hores',
    methodology: ['Teoria','Casos pràctics'],
    organization: 'ESCI-UPF',
    startDate: '01/01/2023',
    endDate: '01/03/2023',
    teachers: ['ESCI-UPF'],
    level: 'Avançat',
    // link: 'https://www.esci.upf.edu/es/cursos-postgrados/postgrado-gestion-transicion-sostenible-emergencia-climatica/pgsc-presentacion',
  },
  {
    title: 'Formació 2',
    summary: 'This is a formation card. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat sed voluptates, nobis iure veniam animi magni assumenda eos ipsam quos. Tenetur, error alias?',
    img: 'https://picsum.photos/seed/picsum/200/300',
    modality: 'Online',
    lenguage: 'Català',
    price: '230',
    duration: '20 hores',
    methodology: 'Casos pràctics',
    organization: 'Organització 2',
    startDate: '01/01/2021',
    endDate: '01/02/2021',
    teachers: ['Teacher 1', 'Teacher 2'],
    level: 'Bàsic',
  },
  {
    title: 'Formació 3',
    summary: 'This is a formation card. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat sed voluptates, nobis iure veniam animi magni assumenda eos ipsam quos. Tenetur, error alias?',
    img: 'https://picsum.photos/seed/picsum/200/300',
    modality: 'Presencial',
    lenguage: 'Català',
    price: 'Gratuït',
    duration: '20 hores',
    methodology: 'Casos pràctics',
    organization: 'Organització 3',
    startDate: '01/01/2021',
    endDate: '01/02/2021',
    teachers: ['Teacher 1', 'Teacher 2'],
    level: 'Mitjà',
  },
];