export { default as Biblio } from './Biblio';
export { default as MethodologyList } from './Methodology/MethodologyList';
export { default as MethodologyView } from './Methodology/MethodologyView';
export { default as PracticeAdd } from './Practice/PracticeAdd';
export { default as PracticeList } from './Practice/PracticeList';
export { default as PracticeView } from './Practice/PracticeView';
export { default as NewsList } from './News/NewsList';
export { default as PostAdd } from './News/PostAdd';
export { default as PostView } from './News/PostView';